use climedic;
insert into exame (exame) values ('Glicose');
insert into exame (exame) values ('Hemoglobina Glicada');
insert into exame (exame) values ('Ureia');
insert into exame (exame) values ('Creatinina');
insert into exame (exame) values ('Sódio');
insert into exame (exame) values ('Colesterol total+frações');
insert into exame (exame) values ('Acido Úrico');
insert into exame (exame) values ('TGO');
insert into exame (exame) values ('TGP');
insert into exame (exame) values ('Fosfatase Alcalina');
insert into exame (exame) values ('GGT');
insert into exame (exame) values ('CK');
insert into exame (exame) values ('Fosforo');
insert into exame (exame) values ('Ferro');
insert into exame (exame) values ('Amilase');
insert into exame (exame) values ('Hemograma Completo');
insert into exame (exame) values ('Coagulograma');
insert into exame (exame) values ('Urina');
insert into exame (exame) values ('Urocultura');
insert into exame (exame) values ('Antibiograma');